spring:
  application:
    name: Help Desk Backend

  profiles:
    active: prod

server:
  port: 8081

logging:
  level:
    com.ai.helpDesk: INFO
    org.springframework.ai.chat.client.advisor:
      SimpleLoggerAdvisor:
