spring:
  datasource:
    url:  jdbc:postgresql://dpg-d5f0r6ali9vc73d94n10-a:5432/helpdesk_d30y_96j3
    username: helpdesk_d30y_96j3_user
    password: DOn7nSbT1a8GYPis3cXvcMKk0DHVVKxe

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect






  ai:
    openai:
      api-key: ${OPENAI_API_KEY}        # Set this in Render environment
      base-url: https://api.openai.com
      chat:
        enabled: true
        model: gpt-4o-mini

    google:
      genai:
        api-key: ${GOOGLE_API_KEY}      # Set this in Render environment
        project-id: gen-lang-client-0441575655
        chat:
          enabled: true
          model: gemini-1.5-flash
    retry:
      enabled: false

server:
  port: 8081

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
