spring:
  application:
    name: Help Desk Backend

  datasource:
    url: jdbc:mysql://localhost:3306/helpDesk
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: https://api.openai.com
      chat:
        enabled: true
        model: gpt-4o-mini

    google:
      genai:
        api-key: ${GOOGLE_API_KEY}
        project-id: gen-lang-client-0441575655
        chat:
          enabled: true
          model: gemini-1.5-flash

server:
  port: 8081
